FROM node:20-alpine as build
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
CMD ["serve", "-s", "build", "-l", "3000"]


FROM nginx:latest
COPY --from=build /usr/src/app/build /usr/share/nginx/html
COPY ./nginx/nginx.prod.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
