version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    command: npm start
    expose:
      - 3001
    environment:
      - PORT=3001
      - HOST=localhost
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    command: serve -s build -l 3000
    ports:
     - "3000:3000"
    volumes:
    - ./frontend/build:/usr/share/nginx/html
    depends_on:
    - api

  api_db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_api:/data/db
  
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - api
    ports:
      - "80:80"

volumes:
  mongodb_api:



    # Данилевич Іван ІПЗм-24-2
