services:
  api:
    container_name: api_dev
    image: node:20
    working_dir: /usr/src/app
    command: /usr/bin/bash -c "npm i && npm run start"
    ports:
      - "3001:3001"
    volumes:
      - ./api:/usr/src/app
    environment:
      NODE_ENV: development
    depends_on:
    - api_db 
  api_db:
    container_name: api_db_dev
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_api:/data/db
  frontend:
    container_name: frontend_dev
    image: node:20
    working_dir: /usr/src/app
    command: /usr/bin/bash -c "npm i && npm start"
    ports:
    - "3000:3000"
    volumes:
    - ./frontend:/usr/src/app
    environment:
    - CHOKIDAR_USEPOLLING=true
    - NODE_ENV=development
    - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - api
  nginx:
    image: nginx:latest
    container_name: nginx_dev
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - api
    ports:
      - "80:80"
volumes:
  mongodb_api: