services:
  api:
    container_name: api
    image: node:20
    working_dir: /usr/src/app
    command: /usr/bin/bash -c "npm i && npm start"
    volumes:
    - ./api:/usr/src/app
    expose:
      - 3001
    environment: 
      - PORT=3001
      - HOST=localhost
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db

  frontend:
    image: node:20
    working_dir: /usr/src/app
    container_name: frontend
    command: /usr/bin/bash -c "npm i && npm run build"
    volumes:
    - ./frontend:/usr/src/app
    depends_on:
    - api

  api_db:
    container_name: api_db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_api:/data/db
  
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/src/app
    depends_on:
      - frontend
      - api
    ports:
      - "80:80"

volumes:
  mongodb_api:



    # Данилевич Іван ІПЗм-24-2
