version: "3.8"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./api:/usr/src/app
    command: npm run dev
    environment:
      NODE_ENV: development
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run start
    ports:
    - "3000:3000"
    volumes:
    - ./frontend:/usr/src/app
    environment:
    - CHOKIDAR_USEPOLLING=true
    - NODE_ENV=development
    - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - api
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - api
    ports:
      - "80:80"